name: AWS Login with OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: arn:aws:iam::077957416427:role/gh-actions
          aws-region: us-west-2
      - name: Additional steps
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity 